server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      # 将自己注册到eureka-server1、eureka-server2这个Eureka上面去
      defaultZone: http://localhost:10086/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护